server:
  port: 18080
  servlet:
    context-path: /  # 确保没有额外的基础路径

spring:
  application:
    name: spring-ai-alibaba-openmanus

  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-latest

logging:
  level:
    com.alibaba.cloud.ai.example.manus: DEBUG  # 增加日志级别以便调试
    org.springframework.web: INFO
manus:
  browser:
    headless: false  # 设置为 true 则启用无头模式
